# Linear Regression Model

# I.Load data

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# target to show plot in jupyter notebook and not external window
%matplotlib inline 

import warnings
warnings.filterwarnings('ignore')

In [2]:
df_data = pd.read_csv("data_predict_price_house.csv")
# Display the first few rows of the dataframe
df_data.head()

quan  dien_tich_dat_m2  dien_tich_su_dung_m2  phong_ngu  nha_tam   gia
0   Gò Vấp             147.0                 479.0       17.0     18.0  16.8
1  Tân Phú             180.0                 179.0       13.0     13.0  23.0
2       10              53.0                  53.0        2.0      2.0   4.3
3        9             233.0                 233.0       28.0     28.0  26.0
4       10             102.0                 102.0        2.0      2.0   3.7

In [3]:
# Print the shape of the dataframe
print(df_data.shape)

(4293, 6)


In [4]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4293 entries, 0 to 4292
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   quan                  4293 non-null   object 
 1   dien_tich_dat_m2      4293 non-null   float64
 2   dien_tich_su_dung_m2  4293 non-null   float64
 3   phong_ngu             4293 non-null   float64
 4   nha_tam               4293 non-null   float64
 5   gia                   4293 non-null   float64
dtypes: float64(5), object(1)
memory usage: 201.4+ KB


In [5]:
# Get the names of non-object (numerical) columns
df_data.select_dtypes(exclude=['object']).shape

(4293, 5)

In [6]:
df_data.select_dtypes(exclude=['object']).columns

Index(['dien_tich_dat_m2', 'dien_tich_su_dung_m2', 'phong_ngu', 'nha_tam',
       'gia'],
      dtype='object')

In [7]:
# Get the names of object (non-numerical) columns
df_data.select_dtypes(include=['object']).shape

(4293, 1)

In [8]:
df_data.select_dtypes(include=['object']).columns

Index(['quan'], dtype='object')

In [9]:
print(df_data['quan'].unique())
df_data['quan'].value_counts()

['Gò Vấp' 'Tân Phú' '10' '9' 'Bình Tân' '5' '7' 'Phú Nhuận' '3'
 'Bình Thạnh' '1' '2' '4' '6' '8' '11' '12' 'Tân Bình'
 'Thủ Đức (TP. Thủ Đức)']


quan
9                        358
6                        334
4                        300
1                        294
8                        278
12                       266
11                       261
Tân Phú                  251
5                        230
2                        221
7                        210
10                       190
Tân Bình                 186
Bình Tân                 184
Phú Nhuận                180
Thủ Đức (TP. Thủ Đức)    157
Bình Thạnh               137
Gò Vấp                   128
3                        128
Name: count, dtype: int64

In [10]:
# Get summary statistics of numerical columns
df_data.describe()

dien_tich_dat_m2  dien_tich_su_dung_m2    phong_ngu      nha_tam  \
count       4293.000000          4.293000e+03  4293.000000  4293.000000   
mean         126.256615          5.513882e+02     4.610063     4.554391   
std          295.298250          1.831914e+04     4.999423     5.284465   
min            1.000000          1.000000e+00     1.000000     1.000000   
25%           58.000000          8.200000e+01     3.000000     2.000000   
50%           78.000000          1.390000e+02     4.000000     3.000000   
75%          120.000000          2.900000e+02     5.000000     5.000000   
max        10000.000000          1.200000e+06   100.000000   100.000000   

                gia  
count   4293.000000  
mean      29.863489  
std      324.805015  
min        0.000000  
25%        5.100000  
50%        9.700000  
75%       22.000000  
max    20972.000000

In [11]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4293 entries, 0 to 4292
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   quan                  4293 non-null   object 
 1   dien_tich_dat_m2      4293 non-null   float64
 2   dien_tich_su_dung_m2  4293 non-null   float64
 3   phong_ngu             4293 non-null   float64
 4   nha_tam               4293 non-null   float64
 5   gia                   4293 non-null   float64
dtypes: float64(5), object(1)
memory usage: 201.4+ KB


In [12]:
df_data.describe()

dien_tich_dat_m2  dien_tich_su_dung_m2    phong_ngu      nha_tam  \
count       4293.000000          4.293000e+03  4293.000000  4293.000000   
mean         126.256615          5.513882e+02     4.610063     4.554391   
std          295.298250          1.831914e+04     4.999423     5.284465   
min            1.000000          1.000000e+00     1.000000     1.000000   
25%           58.000000          8.200000e+01     3.000000     2.000000   
50%           78.000000          1.390000e+02     4.000000     3.000000   
75%          120.000000          2.900000e+02     5.000000     5.000000   
max        10000.000000          1.200000e+06   100.000000   100.000000   

                gia  
count   4293.000000  
mean      29.863489  
std      324.805015  
min        0.000000  
25%        5.100000  
50%        9.700000  
75%       22.000000  
max    20972.000000

In [13]:
df_clean = df_data[
    (df_data['dien_tich_dat_m2'] <= 1000) &
    (df_data['dien_tich_su_dung_m2'] <= 2000) &
    (df_data['phong_ngu'] <= 10) &
    (df_data['nha_tam'] <= 10)
]
print(df_clean.shape)

(4011, 6)


In [14]:
df_clean.head()

quan  dien_tich_dat_m2  dien_tich_su_dung_m2  phong_ngu  nha_tam  gia
2   10              53.0                  53.0        2.0      2.0  4.3
4   10             102.0                 102.0        2.0      2.0  3.7
5   10              79.0                  79.0        2.0      2.0  4.9
6   10              72.0                  72.0        2.0      2.0  5.5
7   10             103.0                 103.0        3.0      2.0  8.2

In [15]:
df_clean.describe()

dien_tich_dat_m2  dien_tich_su_dung_m2    phong_ngu      nha_tam  \
count       4011.000000           4011.000000  4011.000000  4011.000000   
mean         101.288369            212.188125     3.744453     3.621541   
std           92.054532            233.141943     1.768036     1.928491   
min            1.000000              1.000000     1.000000     1.000000   
25%           57.000000             80.000000     2.500000     2.000000   
50%           75.000000            130.000000     3.000000     3.000000   
75%          110.000000            250.000000     5.000000     5.000000   
max         1000.000000           2000.000000    10.000000    10.000000   

                gia  
count   4011.000000  
mean      26.407791  
std      333.986253  
min        0.000000  
25%        4.900000  
50%        8.990000  
75%       18.500000  
max    20972.000000

# Pre-processing data

+ Ở đây có 2 trường hợp:
    + Muốn sử dụng full data để train thì: 
    
        data = df_data.copy()
    
    + Muốn sử dụng data sau khi lọc thì:
    
        data = df_clean.copy()
    

In [16]:
data = df_clean.copy()

## Slipt data into train and test

### Slip train and test

In [17]:
# Create training and validation sets
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(
    data, 
    test_size=0.2, 
    random_state=42)
print("Train data shape:", train_data.shape)
print("Test data shape:", test_data.shape)

Train data shape: (3208, 6)
Test data shape: (803, 6)


### Extract label is gia and drop in feature

In [18]:
y_train = train_data['gia'].values
y_test = test_data['gia'].values
train_data = train_data.drop(columns=['gia'], axis=1)
test_data = test_data.drop(columns=['gia'], axis=1)


In [19]:
train_data.shape, test_data.shape

((3208, 5), (803, 5))

### Check train data having value is non-numeric or other type

In [20]:
num_cols = [col for col in train_data.columns if train_data[col].dtype in ["float64","int64"]]
cat_cols = [col for col in train_data.columns if train_data[col].dtype not in ["float64","int64"]]

In [21]:
len(num_cols), len(cat_cols)

(4, 1)

In [22]:
# fill none for categorical columns
train_data[cat_cols] = train_data[cat_cols].fillna("none")
test_data[cat_cols] = test_data[cat_cols].fillna("none")

In [23]:
print("X_train shape:", train_data.shape)
print("X_test shape:", test_data.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (3208, 5)
X_test shape: (803, 5)
y_train shape: (3208,)
y_test shape: (803,)


### One-hot encoding feature "quan"

+ Nếu gặp một cái mới ở test thì set one-hot là 0

#### One-hot encoding with catery in quan

In [24]:
from sklearn.preprocessing import OneHotEncoder

### One-hot encoding feature "quan"
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoder.fit(train_data[cat_cols])

encoder_cols = list(encoder.get_feature_names_out(cat_cols))
train_data[encoder_cols] = encoder.transform(train_data[cat_cols])
test_data[encoder_cols] = encoder.transform(test_data[cat_cols])

#### Transform value "Nan":

In [25]:
from sklearn.preprocessing import OneHotEncoder

# One-hot encode categorical columns
encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
encoder.fit(train_data[cat_cols])

encoded_cols = list(encoder.get_feature_names_out(cat_cols))

train_data[encoded_cols] = encoder.transform(train_data[cat_cols])
test_data[encoded_cols] = encoder.transform(test_data[cat_cols])

#### Print infor

In [26]:
train_data

quan  dien_tich_dat_m2  dien_tich_su_dung_m2  \
650                       4              55.0                 165.0   
1534                      8              53.0                  53.0   
2339                     12              30.0                  50.0   
1702                      8             120.0                 600.0   
1699                      8              61.0                 122.0   
...                     ...               ...                   ...   
1182                      6              80.0                  80.0   
1357                      7              60.0                 120.0   
901                       5              68.0                 136.0   
3751  Thủ Đức (TP. Thủ Đức)              20.0                  31.0   
3395                Tân Phú             127.0                 381.0   

      phong_ngu  nha_tam  quan_1  quan_10  quan_11  quan_12  quan_2  ...  \
650         4.0      3.0     0.0      0.0      0.0      0.0     0.0  ...   
1534        2.0      2.0     0.0      0.0      0.0      0.0     0.0  ...   
2339        2.0      2.0     0.0      0.0      0.0      1.0     0.0  ...   
1702        3.0      4.0     0.0      0.0      0.0      0.0     0.0  ...   
1699        3.0      2.0     0.0      0.0      0.0      0.0     0.0  ...   
...         ...      ...     ...      ...      ...      ...     ...  ...   
1182        2.0      2.0     0.0      0.0      0.0      0.0     0.0  ...   
1357        3.0      3.0     0.0      0.0      0.0      0.0     0.0  ...   
901         2.0      2.0     0.0      0.0      0.0      0.0     0.0  ...   
3751        2.0      1.0     0.0      0.0      0.0      0.0     0.0  ...   
3395        3.0      3.0     0.0      0.0      0.0      0.0     0.0  ...   

      quan_7  quan_8  quan_9  quan_Bình Thạnh  quan_Bình Tân  quan_Gò Vấp  \
650      0.0     0.0     0.0              0.0            0.0          0.0   
1534     0.0     1.0     0.0              0.0            0.0          0.0   
2339     0.0     0.0     0.0              0.0            0.0          0.0   
1702     0.0     1.0     0.0              0.0            0.0          0.0   
1699     0.0     1.0     0.0              0.0            0.0          0.0   
...      ...     ...     ...              ...            ...          ...   
1182     0.0     0.0     0.0              0.0            0.0          0.0   
1357     1.0     0.0     0.0              0.0            0.0          0.0   
901      0.0     0.0     0.0              0.0            0.0          0.0   
3751     0.0     0.0     0.0              0.0            0.0          0.0   
3395     0.0     0.0     0.0              0.0            0.0          0.0   

      quan_Phú Nhuận  quan_Thủ Đức (TP. Thủ Đức)  quan_Tân Bình  quan_Tân Phú  
650              0.0                         0.0            0.0           0.0  
1534             0.0                         0.0            0.0           0.0  
2339             0.0                         0.0            0.0           0.0  
1702             0.0                         0.0            0.0           0.0  
1699             0.0                         0.0            0.0           0.0  
...              ...                         ...            ...           ...  
1182             0.0                         0.0            0.0           0.0  
1357             0.0                         0.0            0.0           0.0  
901              0.0                         0.0            0.0           0.0  
3751             0.0                         1.0            0.0           0.0  
3395             0.0                         0.0            0.0           1.0  

[3208 rows x 24 columns]

In [27]:
test_data

quan  dien_tich_dat_m2  dien_tich_su_dung_m2  phong_ngu  nha_tam  \
336            2              72.0                  72.0        2.0      2.0   
2753  Bình Thạnh             249.0                1000.0        7.0      7.0   
3090   Phú Nhuận              64.0                 128.0        3.0      4.0   
2629    Bình Tân              96.0                  96.0        2.0      1.0   
3470     Tân Phú              32.0                  60.0        2.0      2.0   
...          ...               ...                   ...        ...      ...   
1482           7             140.0                 140.0        5.0      5.0   
294            2              98.0                  98.0        2.0      2.0   
743            4             105.0                 105.0        3.0      2.0   
285            2             433.0                 433.0        4.0      4.0   
3186   Phú Nhuận              43.0                 120.0        4.0      5.0   

      quan_1  quan_10  quan_11  quan_12  quan_2  ...  quan_7  quan_8  quan_9  \
336      0.0      0.0      0.0      0.0     1.0  ...     0.0     0.0     0.0   
2753     0.0      0.0      0.0      0.0     0.0  ...     0.0     0.0     0.0   
3090     0.0      0.0      0.0      0.0     0.0  ...     0.0     0.0     0.0   
2629     0.0      0.0      0.0      0.0     0.0  ...     0.0     0.0     0.0   
3470     0.0      0.0      0.0      0.0     0.0  ...     0.0     0.0     0.0   
...      ...      ...      ...      ...     ...  ...     ...     ...     ...   
1482     0.0      0.0      0.0      0.0     0.0  ...     1.0     0.0     0.0   
294      0.0      0.0      0.0      0.0     1.0  ...     0.0     0.0     0.0   
743      0.0      0.0      0.0      0.0     0.0  ...     0.0     0.0     0.0   
285      0.0      0.0      0.0      0.0     1.0  ...     0.0     0.0     0.0   
3186     0.0      0.0      0.0      0.0     0.0  ...     0.0     0.0     0.0   

      quan_Bình Thạnh  quan_Bình Tân  quan_Gò Vấp  quan_Phú Nhuận  \
336               0.0            0.0          0.0             0.0   
2753              1.0            0.0          0.0             0.0   
3090              0.0            0.0          0.0             1.0   
2629              0.0            1.0          0.0             0.0   
3470              0.0            0.0          0.0             0.0   
...               ...            ...          ...             ...   
1482              0.0            0.0          0.0             0.0   
294               0.0            0.0          0.0             0.0   
743               0.0            0.0          0.0             0.0   
285               0.0            0.0          0.0             0.0   
3186              0.0            0.0          0.0             1.0   

      quan_Thủ Đức (TP. Thủ Đức)  quan_Tân Bình  quan_Tân Phú  
336                          0.0            0.0           0.0  
2753                         0.0            0.0           0.0  
3090                         0.0            0.0           0.0  
2629                         0.0            0.0           0.0  
3470                         0.0            0.0           1.0  
...                          ...            ...           ...  
1482                         0.0            0.0           0.0  
294                          0.0            0.0           0.0  
743                          0.0            0.0           0.0  
285                          0.0            0.0           0.0  
3186                         0.0            0.0           0.0  

[803 rows x 24 columns]

# Normalization

+ Mục tiêu đưa các giá trị về [0, 1]
+ Chuẩn hoá theo min, max
+ value_new = (value_old - min)/(max - min)

## Norm

In [28]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

train_num_feature = scaler.fit_transform(train_data[num_cols])
test_num_feature = scaler.transform(test_data[num_cols])

In [29]:
print("X_train shape:", train_num_feature.shape)
print("X_test shape:", test_num_feature.shape)

X_train shape: (3208, 4)
X_test shape: (803, 4)


In [30]:
train_num_feature

array([[0.05405405, 0.08204102, 0.33333333, 0.22222222],
       [0.05205205, 0.02601301, 0.11111111, 0.11111111],
       [0.02902903, 0.02451226, 0.11111111, 0.11111111],
       ...,
       [0.06706707, 0.06753377, 0.11111111, 0.11111111],
       [0.01901902, 0.0150075 , 0.11111111, 0.        ],
       [0.12612613, 0.19009505, 0.22222222, 0.22222222]])

In [31]:
test_num_feature

array([[0.07107107, 0.03551776, 0.11111111, 0.11111111],
       [0.24824825, 0.49974987, 0.66666667, 0.66666667],
       [0.06306306, 0.06353177, 0.22222222, 0.33333333],
       ...,
       [0.1041041 , 0.05202601, 0.22222222, 0.11111111],
       [0.43243243, 0.21610805, 0.33333333, 0.33333333],
       [0.04204204, 0.05952976, 0.33333333, 0.44444444]])

## Add X_train, X_test

In [32]:
X_train = np.hstack([train_num_feature, train_data[encoder_cols].values])
X_test = np.hstack([test_num_feature, test_data[encoder_cols].values])

In [33]:
X_train.shape, X_test.shape

((3208, 23), (803, 23))

In [34]:
X_train

array([[0.05405405, 0.08204102, 0.33333333, ..., 0.        , 0.        ,
        0.        ],
       [0.05205205, 0.02601301, 0.11111111, ..., 0.        , 0.        ,
        0.        ],
       [0.02902903, 0.02451226, 0.11111111, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.06706707, 0.06753377, 0.11111111, ..., 0.        , 0.        ,
        0.        ],
       [0.01901902, 0.0150075 , 0.11111111, ..., 1.        , 0.        ,
        0.        ],
       [0.12612613, 0.19009505, 0.22222222, ..., 0.        , 0.        ,
        1.        ]])

In [35]:
X_test

array([[0.07107107, 0.03551776, 0.11111111, ..., 0.        , 0.        ,
        0.        ],
       [0.24824825, 0.49974987, 0.66666667, ..., 0.        , 0.        ,
        0.        ],
       [0.06306306, 0.06353177, 0.22222222, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.1041041 , 0.05202601, 0.22222222, ..., 0.        , 0.        ,
        0.        ],
       [0.43243243, 0.21610805, 0.33333333, ..., 0.        , 0.        ,
        0.        ],
       [0.04204204, 0.05952976, 0.33333333, ..., 0.        , 0.        ,
        0.        ]])

In [36]:
y_train

array([ 1.1  ,  1.739,  1.38 , ...,  1.24 ,  1.8  , 19.5  ])

In [37]:
y_test

array([5.99900e+00, 6.30000e+01, 5.00000e+01, 7.98000e+00, 3.59000e+00,
       2.45500e+00, 6.50000e+00, 1.55000e+01, 2.90000e+00, 9.80000e+00,
       4.60000e+00, 9.28000e-01, 8.60000e+00, 1.80000e+01, 1.45000e+01,
       4.50000e+00, 7.50000e+00, 5.90000e+01, 2.69000e+00, 1.89000e+00,
       8.80000e-01, 2.65000e+01, 2.25000e+01, 5.10000e+00, 3.40000e+01,
       5.90000e+00, 3.60000e+01, 4.30000e+00, 2.75000e+00, 7.90000e+00,
       9.70000e-01, 9.50000e+00, 4.80000e+00, 9.98000e+00, 1.10000e+01,
       6.70000e+00, 1.90000e+01, 2.00000e+01, 3.20000e+00, 1.68000e+01,
       1.50000e+01, 8.70000e+00, 1.70500e+00, 1.03300e+00, 7.80000e+01,
       8.90000e+00, 1.00000e-01, 8.90000e+00, 1.20000e+01, 3.35000e+01,
       5.35000e+00, 6.58000e+00, 9.90000e+00, 4.40000e+00, 9.10000e+00,
       2.80000e+01, 1.29000e+01, 5.00000e+01, 7.95000e+00, 3.79990e+01,
       6.99900e+00, 9.70000e-01, 2.30000e+01, 2.28000e+00, 1.55000e+01,
       2.25000e+01, 3.60000e+01, 3.95000e+00, 5.50000e+00, 8.200

# Train Regression Model

+ Ridge = Linear Regression + L2 regularization

+ Lasso = Linear Regression + L1 regularization

## Setup model

In [38]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
import pandas as pd

# Tạo danh sách model
models = {
    "LinearRegression": LinearRegression(),
    "Ridge": Ridge(),
    "Lasso": Lasso()
}

# List storage for results
train_rmse_results = []
test_rmse_results = []
train_r2_results = []
test_r2_results = []
model_names = []

## Training model

+ Hàm fit() ở đây dùng để train model bằng cách:
    +  Giải một hệ phương trình tuyến tính để tìm w tốt nhất (ít sai số bình phương nhất).
    + w_best = (X^T * X)^{-1} * X^T * y - với linear và 2 còn lại là thêm regularization.

In [39]:
# Tạo thư mục lưu mô hình
import os
folder_path_save = "Models"
if not os.path.exists(folder_path_save):
    os.makedirs(folder_path_save)


In [40]:
import joblib # Lib save model
    
def train_and_evaluate(models, X_train, y_train, X_test, y_test, folder_path_save="Models"):
    model_names = []
    train_rmse_results = []
    test_rmse_results = []
    train_r2_results = []
    test_r2_results = []

    for name, model in models.items():
        # Train model
        regression = model.fit(X_train, y_train)
        joblib.dump(regression, f"{folder_path_save}/house_price_{name}_model.joblib")

        # Predict
        y_train_pred = regression.predict(X_train)
        y_test_pred = regression.predict(X_test)
        # Calculate metrics
        train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
        test_rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))

        # R^2 score
        train_r2 = r2_score(y_train, y_train_pred)
        test_r2 = r2_score(y_test, y_test_pred)

        # Store results
        model_names.append(name)
        train_rmse_results.append(train_rmse)
        test_rmse_results.append(test_rmse)
        train_r2_results.append(train_r2)
        test_r2_results.append(test_r2)

    
    # Create results DataFrame
    results_df = pd.DataFrame({
        "Model": model_names,
        "Train RMSE": train_rmse_results,
        "Test RMSE": test_rmse_results,
        "Train R2": train_r2_results,
        "Test R2": test_r2_results
    }).sort_values(by="Test R2", ascending=False)
    return results_df



In [41]:
result = train_and_evaluate(models, X_train, y_train, X_test, y_test, folder_path_save)
result

Model  Train RMSE  Test RMSE  Train R2   Test R2
2             Lasso  370.877949  32.921765  0.010738  0.282400
1             Ridge  370.578637  34.508344  0.012334  0.211567
0  LinearRegression  370.576393  34.933773  0.012346  0.192007

## Training Poly-nomial Regression Model

In [42]:
train_data[num_cols]

dien_tich_dat_m2  dien_tich_su_dung_m2  phong_ngu  nha_tam
650               55.0                 165.0        4.0      3.0
1534              53.0                  53.0        2.0      2.0
2339              30.0                  50.0        2.0      2.0
1702             120.0                 600.0        3.0      4.0
1699              61.0                 122.0        3.0      2.0
...                ...                   ...        ...      ...
1182              80.0                  80.0        2.0      2.0
1357              60.0                 120.0        3.0      3.0
901               68.0                 136.0        2.0      2.0
3751              20.0                  31.0        2.0      1.0
3395             127.0                 381.0        3.0      3.0

[3208 rows x 4 columns]

## Init model poly-monial

+ Using model degree 2

In [43]:
from sklearn.preprocessing import PolynomialFeatures
poly_features = PolynomialFeatures(degree=2, include_bias=False, interaction_only=True)
train_poly_feat = poly_features.fit_transform(train_data[num_cols])
test_poly_feat = poly_features.transform(test_data[num_cols])

In [44]:
train_poly_feat

array([[  55.,  165.,    4., ...,  660.,  495.,   12.],
       [  53.,   53.,    2., ...,  106.,  106.,    4.],
       [  30.,   50.,    2., ...,  100.,  100.,    4.],
       ...,
       [  68.,  136.,    2., ...,  272.,  272.,    4.],
       [  20.,   31.,    2., ...,   62.,   31.,    2.],
       [ 127.,  381.,    3., ..., 1143., 1143.,    9.]])

In [45]:
test_poly_feat

array([[7.200e+01, 7.200e+01, 2.000e+00, ..., 1.440e+02, 1.440e+02,
        4.000e+00],
       [2.490e+02, 1.000e+03, 7.000e+00, ..., 7.000e+03, 7.000e+03,
        4.900e+01],
       [6.400e+01, 1.280e+02, 3.000e+00, ..., 3.840e+02, 5.120e+02,
        1.200e+01],
       ...,
       [1.050e+02, 1.050e+02, 3.000e+00, ..., 3.150e+02, 2.100e+02,
        6.000e+00],
       [4.330e+02, 4.330e+02, 4.000e+00, ..., 1.732e+03, 1.732e+03,
        1.600e+01],
       [4.300e+01, 1.200e+02, 4.000e+00, ..., 4.800e+02, 6.000e+02,
        2.000e+01]])

In [46]:
X_train_poly = np.hstack([train_poly_feat, train_data[encoder_cols].values])
X_test_poly = np.hstack([test_poly_feat, test_data[encoder_cols].values])

In [47]:
X_train_poly

array([[ 55., 165.,   4., ...,   0.,   0.,   0.],
       [ 53.,  53.,   2., ...,   0.,   0.,   0.],
       [ 30.,  50.,   2., ...,   0.,   0.,   0.],
       ...,
       [ 68., 136.,   2., ...,   0.,   0.,   0.],
       [ 20.,  31.,   2., ...,   1.,   0.,   0.],
       [127., 381.,   3., ...,   0.,   0.,   1.]])

In [48]:
X_train_poly.shape, X_test_poly.shape

((3208, 29), (803, 29))

In [49]:
y_train.shape, y_test.shape

((3208,), (803,))

In [50]:
# making dictionary of models
models = {
    "LinearRegression_poly": LinearRegression(),
    "Ridge_poly": Ridge(),
    "Lasso_poly": Lasso()
}
result_poly = train_and_evaluate(models, X_train_poly, y_train, X_test_poly, y_test, folder_path_save)
result_final = pd.concat([result, result_poly], axis=0).sort_values(by="Test R2", ascending=False)

In [51]:
result_final

Model  Train RMSE  Test RMSE  Train R2   Test R2
2                  Lasso  370.877949  32.921765  0.010738  0.282400
1                  Ridge  370.578637  34.508344  0.012334  0.211567
0       LinearRegression  370.576393  34.933773  0.012346  0.192007
1             Ridge_poly  370.361302  37.208977  0.013493  0.083333
0  LinearRegression_poly  370.361278  37.247702  0.013493  0.081423
2             Lasso_poly  370.530168  37.506230  0.012593  0.068628

# Nhận xét:

+ Về mặt metric tốt nhất: LinearRegression_poly

+ Về mặt ổn định/regularization: Ridge_poly cũng là lựa chọn rất hợp lý (gần như ngang nhau).
+ Nhóm sử dụng các chỉ số RMSE và R² trên tập validation/test để chọn mô hình.
Trong các mô hình so sánh, LinearRegression_poly cho Test RMSE thấp nhất (~28.40) và Test R² cao nhất (~0.615), do đó được chọn là mô hình tốt nhất cho bài toán này.

+ Mô hình Ridge_poly cho kết quả rất gần tương đương, có thể được cân nhắc khi ưu tiên tính ổn định do có regularization L2.

# Full pipeline from normalization to predict

In [52]:
data_model = data.copy()

In [53]:
data_model

quan  dien_tich_dat_m2  dien_tich_su_dung_m2  phong_ngu  nha_tam   gia
2      10              53.0                  53.0        2.0      2.0   4.3
4      10             102.0                 102.0        2.0      2.0   3.7
5      10              79.0                  79.0        2.0      2.0   4.9
6      10              72.0                  72.0        2.0      2.0   5.5
7      10             103.0                 103.0        3.0      2.0   8.2
...   ...               ...                   ...        ...      ...   ...
4288    1              50.0                  50.0        1.0      1.0   5.6
4289    1              50.0                  50.0        1.0      1.0   6.0
4290    1              72.0                  72.0        2.0      2.0   8.0
4291    1             121.0                 121.0        3.0      2.0  16.5
4292    1              80.0                  80.0        2.0      2.0  11.0

[4011 rows x 6 columns]

In [54]:
# Create training and validation sets
from sklearn.model_selection import train_test_split

train_data_new, test_data_new = train_test_split(
    data_model, 
    test_size=0.2, 
    random_state=42)
print("Train data shape:", train_data_new.shape)
print("Test data shape:", test_data_new.shape)

Train data shape: (3208, 6)
Test data shape: (803, 6)


In [55]:
y_train_new = train_data_new['gia'].values
y_test_new = test_data_new['gia'].values
train_data_new = train_data_new.drop(columns=['gia'], axis=1)
test_data_new = test_data_new.drop(columns=['gia'], axis=1)


In [56]:
print("X_train shape:", train_data_new.shape)
print("X_test shape:", test_data_new.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (3208, 5)
X_test shape: (803, 5)
y_train shape: (3208,)
y_test shape: (803,)


### Setup model

In [57]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np
import pandas as pd

# Tạo danh sách model
models = {
    "LinearRegression": LinearRegression(),
    "Ridge": Ridge(),
    "Lasso": Lasso()
}
names_list = {
    "LinearRegression": "LinearRegression",
    "Ridge": "Ridge",
    "Lasso": "Lasso",
    "Linear_poly": "LinearRegression",
    "Ridge_poly": "Ridge",
    "Lasso_poly": "Lasso"

}
# List storage for results
train_rmse_results = []
test_rmse_results = []
train_r2_results = []
test_r2_results = []
model_names = []

In [58]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler, PolynomialFeatures
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression

num_cols = ["dien_tich_dat_m2", "dien_tich_su_dung_m2", "phong_ngu", "nha_tam"]
cat_cols = ["quan"]

numeric_transformer_1 = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="mean")),
    ("scaler", MinMaxScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocess_1 = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer_1, num_cols),
        ("cat", categorical_transformer, cat_cols),
    ]
)


### Train model

### Model linear

In [59]:
import joblib # Lib save model

def train_and_evaluate_degree_1(models, X_train_new, y_train_new, X_test_new, y_test_new, folder_path_save="Models", names_list=[], preprocess=None):
    model_names = []
    train_rmse_results = []
    test_rmse_results = []
    train_r2_results = []
    test_r2_results = []


    for name in names_list.keys():
        # Train model
        regression = Pipeline(steps=[
            ("preprocess", preprocess),
            ("regressor", models[names_list[name]])
        ])
        regression = regression.fit(X_train_new, y_train_new)
        joblib.dump(regression, f"{folder_path_save}/house_price_{name}_model.joblib")

        # Predict
        y_train_pred = regression.predict(X_train_new)
        y_test_pred = regression.predict(X_test_new)
        # Calculate metrics
        train_rmse = np.sqrt(mean_squared_error(y_train_new, y_train_pred))
        test_rmse = np.sqrt(mean_squared_error(y_test_new, y_test_pred))

        # R^2 score
        train_r2 = r2_score(y_train_new, y_train_pred)
        test_r2 = r2_score(y_test_new, y_test_pred)
        # Store results
        model_names.append(name)
        train_rmse_results.append(train_rmse)
        test_rmse_results.append(test_rmse)
        train_r2_results.append(train_r2)
        test_r2_results.append(test_r2)

    
    # Create results DataFrame
    results_df = pd.DataFrame({
        "Model": model_names,
        "Train RMSE": train_rmse_results,
        "Test RMSE": test_rmse_results,
        "Train R2": train_r2_results,
        "Test R2": test_r2_results
    }).sort_values(by="Test R2", ascending=False)
    return results_df

In [60]:
names_list_1 = {
    "LinearRegression": "LinearRegression",
    "Ridge": "Ridge",
    "Lasso": "Lasso",
}
result_1 = train_and_evaluate_degree_1(models, train_data_new, y_train_new, test_data_new, y_test_new, folder_path_save, names_list_1, preprocess_1)
result_1

Model  Train RMSE  Test RMSE  Train R2   Test R2
2             Lasso  370.877949  32.921765  0.010738  0.282400
1             Ridge  370.578637  34.508225  0.012334  0.211573
0  LinearRegression  370.576393  34.933762  0.012346  0.192008

### Model poly

In [61]:
numeric_transformer_2 = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="mean")),
    ("poly", PolynomialFeatures(degree=2, include_bias=False, interaction_only=True)),
    ("scaler", MinMaxScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocess_2 = ColumnTransformer(
    transformers=[
        ("cat", categorical_transformer, cat_cols),
        ("num", numeric_transformer_2, num_cols),
    ]
)

In [62]:
import joblib # Lib save model

def train_and_evaluate_poly(models, X_train_new, y_train_new, X_test_new, y_test_new, folder_path_save="Models", names_list=None, preprocess=None):
    model_names = []
    train_rmse_results = []
    test_rmse_results = []
    train_r2_results = []
    test_r2_results = []


    for name in names_list.keys():
        # Train model
        regression = Pipeline(steps=[
            ("preprocess", preprocess),
            ("regressor", models[names_list[name]])
        ])
        regression = regression.fit(X_train_new, y_train_new)
        joblib.dump(regression, f"{folder_path_save}/house_price_{name}_model.joblib")

        # Predict
        y_train_pred = regression.predict(X_train_new)
        y_test_pred = regression.predict(X_test_new)
        # Calculate metrics
        train_rmse = np.sqrt(mean_squared_error(y_train_new, y_train_pred))
        test_rmse = np.sqrt(mean_squared_error(y_test_new, y_test_pred))

        # R^2 score
        train_r2 = r2_score(y_train_new, y_train_pred)
        test_r2 = r2_score(y_test_new, y_test_pred)
        # Store results
        model_names.append(name)
        train_rmse_results.append(train_rmse)
        test_rmse_results.append(test_rmse)
        train_r2_results.append(train_r2)
        test_r2_results.append(test_r2)

    
    # Create results DataFrame
    results_df = pd.DataFrame({
        "Model": model_names,
        "Train RMSE": train_rmse_results,
        "Test RMSE": test_rmse_results,
        "Train R2": train_r2_results,
        "Test R2": test_r2_results
    }).sort_values(by="Test R2", ascending=False)
    return results_df

In [63]:
names_list_poly = {
    "Linear_poly": "LinearRegression",
    "Ridge_poly": "Ridge",
    "Lasso_poly": "Lasso",
}
result_poly = train_and_evaluate_poly(models, train_data_new, y_train_new, test_data_new, y_test_new, folder_path_save, names_list_poly, preprocess_2)
result_poly

Model  Train RMSE  Test RMSE  Train R2   Test R2
2   Lasso_poly  370.877949  32.921782  0.010738  0.282399
1   Ridge_poly  370.435656  35.003770  0.013096  0.188766
0  Linear_poly  370.361278  37.247702  0.013493  0.081423

### 5.4.3 Model 3: Model degree 1 (feature)

## Final Result

In [64]:
result_final

Model  Train RMSE  Test RMSE  Train R2   Test R2
2                  Lasso  370.877949  32.921765  0.010738  0.282400
1                  Ridge  370.578637  34.508344  0.012334  0.211567
0       LinearRegression  370.576393  34.933773  0.012346  0.192007
1             Ridge_poly  370.361302  37.208977  0.013493  0.083333
0  LinearRegression_poly  370.361278  37.247702  0.013493  0.081423
2             Lasso_poly  370.530168  37.506230  0.012593  0.068628

In [65]:
final_result_2 = pd.concat([result_1, result_poly], axis=0).sort_values(by="Test R2", ascending=False)
final_result_2

Model  Train RMSE  Test RMSE  Train R2   Test R2
2             Lasso  370.877949  32.921765  0.010738  0.282400
2        Lasso_poly  370.877949  32.921782  0.010738  0.282399
1             Ridge  370.578637  34.508225  0.012334  0.211573
0  LinearRegression  370.576393  34.933762  0.012346  0.192008
1        Ridge_poly  370.435656  35.003770  0.013096  0.188766
0       Linear_poly  370.361278  37.247702  0.013493  0.081423

In [66]:
# 1. Load lại model y chang app.py
model = joblib.load("Models/house_price_Linear_poly_model.joblib")

# 2. Tạo đúng input như web
input_df = pd.DataFrame({
    "quan": ["1"],
    "dien_tich_dat_m2": [40],
    "dien_tich_su_dung_m2": [200],
    "phong_ngu": [10],
    "nha_tam": [11],
})

y_pred = model.predict(input_df)
print(y_pred)

[10.73795111]


# Model Polynomial + dien_tich_trung_binh_phong, tong_so_phong

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler, PolynomialFeatures
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.base import BaseEstimator, TransformerMixin

# 1. Định nghĩa Class biến đổi dữ liệu (FeatureEngineer)
class FeatureEngineer(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self
    
    def transform(self, X):
        if isinstance(X, np.ndarray):
            feature_names = ['dien_tich_dat_m2', 'dien_tich_su_dung_m2', 'phong_ngu', 'nha_tam', 'quan']
            X = pd.DataFrame(X, columns=feature_names)
            
        X_new = X.copy()
        X_new['dien_tich_trung_binh_phong'] = X_new['dien_tich_su_dung_m2'] / (X_new['phong_ngu'] + 1e-5)
        X_new['tong_so_phong'] = X_new['phong_ngu'] + X_new['nha_tam']
        return X_new

# 2. Hàm huấn luyện và đánh giá
def train_polynomial_model(X_train, y_train, X_test, y_test):
    """
    Hàm xây dựng, huấn luyện mô hình Polynomial Regression với Feature Engineering 
    và trả về kết quả đánh giá chi tiết dạng DataFrame.
    """
    
    # --- 1. Định nghĩa các cột ---
    num_cols_base = ["dien_tich_dat_m2", "dien_tich_su_dung_m2", "phong_ngu", "nha_tam"]
    cat_cols = ["quan"]
    num_cols_eng = num_cols_base + ["dien_tich_trung_binh_phong", "tong_so_phong"]

    # --- 2. Xây dựng Transformers ---
    numeric_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="mean")),
        ("poly", PolynomialFeatures(degree=2, include_bias=False)),
        ("scaler", MinMaxScaler())
    ])

    categorical_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ])

    # --- 3. Preprocessor ---
    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_transformer, num_cols_eng),
            ("cat", categorical_transformer, cat_cols),
        ]
    )

    # --- 4. Pipeline ---
    model_pipeline = Pipeline(steps=[
        ("feature_eng", FeatureEngineer()), 
        ("preprocessor", preprocessor),     
        ("regressor", LinearRegression())   
    ])

    # --- 5. Huấn luyện ---
    if isinstance(y_train, np.ndarray):
        y_train = pd.Series(y_train, name='gia')
        
    model_pipeline.fit(X_train, y_train)
    
    # --- 6. Đánh giá (Tính toán Metrics) ---
    y_train_pred = model_pipeline.predict(X_train)
    y_test_pred = model_pipeline.predict(X_test)
    
    train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
    test_rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))
    train_r2 = r2_score(y_train, y_train_pred)
    test_r2 = r2_score(y_test, y_test_pred)
    
    # --- 7. Tạo DataFrame kết quả ---
    results_df = pd.DataFrame({
        "Model": ["Polynomial_FeatureEng"],
        "Train RMSE": [train_rmse],
        "Test RMSE": [test_rmse],
        "Train R2": [train_r2],
        "Test R2": [test_r2]
    })
    
    print("Huấn luyện và đánh giá hoàn tất.")
    return model_pipeline, results_df

# --- Cách sử dụng ---
# model, result_df = train_polynomial_model(X_train, y_train, X_test, y_test)
# print(result_df)

# 3. Lưu mô hình bằng joblib
# Tạo thư mục Models nếu chưa có
folder_path_save = "Models"
if not os.path.exists(folder_path_save):
    os.makedirs(folder_path_save)

# Đặt tên file mô hình
model_filename = f"{folder_path_save}/house_price_Polynomial_FeatureEng_model.joblib"

# Lưu file
joblib.dump(model, model_filename)


['Models/house_price_Polynomial_FeatureEng_model.joblib']

In [73]:
# 1. Load lại model y chang app.py
model = joblib.load("Models/house_price_Polynomial_FeatureEng_model.joblib")

# 2. Tạo đúng input như web
input_df = pd.DataFrame({
    "quan": ["1"],
    "dien_tich_dat_m2": [40],
    "dien_tich_su_dung_m2": [200],
    "phong_ngu": [10],
    "nha_tam": [11],
})

y_pred = model.predict(input_df)
print(y_pred)

[10.73795111]
