# Linear Regression Model

+ Mục tiêu hiểu rỏ luồng khi train mô hình sẽ như thế nào.

# I.Load data

In [45]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# target to show plot in jupyter notebook and not external window
%matplotlib inline 

import warnings
warnings.filterwarnings('ignore')

## 1. Data normal

In [46]:
df_data = pd.read_csv("./Data/data_predict_price_house.csv")
# Display the first few rows of the dataframe
df_data.head()

quan  dien_tich_dat_m2  dien_tich_su_dung_m2  phong_ngu  nha_tam   gia
0   Gò Vấp             147.0                 479.0       17.0     18.0  16.8
1  Tân Phú             180.0                 179.0       13.0     13.0  23.0
2       10              53.0                  53.0        2.0      2.0   4.3
3        9             233.0                 233.0       28.0     28.0  26.0
4       10             102.0                 102.0        2.0      2.0   3.7

In [47]:
# Print the shape of the dataframe
print(df_data.shape)

(4293, 6)


In [48]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4293 entries, 0 to 4292
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   quan                  4293 non-null   object 
 1   dien_tich_dat_m2      4293 non-null   float64
 2   dien_tich_su_dung_m2  4293 non-null   float64
 3   phong_ngu             4293 non-null   float64
 4   nha_tam               4293 non-null   float64
 5   gia                   4293 non-null   float64
dtypes: float64(5), object(1)
memory usage: 201.4+ KB


In [49]:
# Get the names of non-object (numerical) columns
df_data.select_dtypes(exclude=['object']).shape

(4293, 5)

In [50]:
df_data.select_dtypes(exclude=['object']).columns

Index(['dien_tich_dat_m2', 'dien_tich_su_dung_m2', 'phong_ngu', 'nha_tam',
       'gia'],
      dtype='object')

In [51]:
# Get the names of object (non-numerical) columns
df_data.select_dtypes(include=['object']).shape

(4293, 1)

In [52]:
df_data.select_dtypes(include=['object']).columns

Index(['quan'], dtype='object')

In [53]:
print(df_data['quan'].unique())
df_data['quan'].value_counts()

['Gò Vấp' 'Tân Phú' '10' '9' 'Bình Tân' '5' '7' 'Phú Nhuận' '3'
 'Bình Thạnh' '1' '2' '4' '6' '8' '11' '12' 'Tân Bình'
 'Thủ Đức (TP. Thủ Đức)']


quan
9                        358
6                        334
4                        300
1                        294
8                        278
12                       266
11                       261
Tân Phú                  251
5                        230
2                        221
7                        210
10                       190
Tân Bình                 186
Bình Tân                 184
Phú Nhuận                180
Thủ Đức (TP. Thủ Đức)    157
Bình Thạnh               137
Gò Vấp                   128
3                        128
Name: count, dtype: int64

In [54]:
# Get summary statistics of numerical columns
df_data.describe()

dien_tich_dat_m2  dien_tich_su_dung_m2    phong_ngu      nha_tam  \
count       4293.000000          4.293000e+03  4293.000000  4293.000000   
mean         126.256615          5.513882e+02     4.610063     4.554391   
std          295.298250          1.831914e+04     4.999423     5.284465   
min            1.000000          1.000000e+00     1.000000     1.000000   
25%           58.000000          8.200000e+01     3.000000     2.000000   
50%           78.000000          1.390000e+02     4.000000     3.000000   
75%          120.000000          2.900000e+02     5.000000     5.000000   
max        10000.000000          1.200000e+06   100.000000   100.000000   

               gia  
count  4293.000000  
mean     24.983213  
std      57.364136  
min       0.000000  
25%       5.100000  
50%       9.700000  
75%      22.000000  
max    1279.999000

## 2. Data with clean

In [55]:
df_clean = df_data[
    (df_data['dien_tich_dat_m2'] <= 1000) &
    (df_data['dien_tich_su_dung_m2'] <= 2000) &
    (df_data['phong_ngu'] <= 10) &
    (df_data['nha_tam'] <= 10)
]
print(df_clean.shape)

(4011, 6)


In [56]:
df_clean.head()

quan  dien_tich_dat_m2  dien_tich_su_dung_m2  phong_ngu  nha_tam  gia
2   10              53.0                  53.0        2.0      2.0  4.3
4   10             102.0                 102.0        2.0      2.0  3.7
5   10              79.0                  79.0        2.0      2.0  4.9
6   10              72.0                  72.0        2.0      2.0  5.5
7   10             103.0                 103.0        3.0      2.0  8.2

In [57]:
df_clean.describe()

dien_tich_dat_m2  dien_tich_su_dung_m2    phong_ngu      nha_tam  \
count       4011.000000           4011.000000  4011.000000  4011.000000   
mean         101.288369            212.188125     3.744453     3.621541   
std           92.054532            233.141943     1.768036     1.928491   
min            1.000000              1.000000     1.000000     1.000000   
25%           57.000000             80.000000     2.500000     2.000000   
50%           75.000000            130.000000     3.000000     3.000000   
75%          110.000000            250.000000     5.000000     5.000000   
max         1000.000000           2000.000000    10.000000    10.000000   

               gia  
count  4011.000000  
mean     21.184398  
std      45.973800  
min       0.000000  
25%       4.900000  
50%       8.990000  
75%      18.500000  
max    1279.999000

# II Pre-processing data

+ Ở đây có 2 trường hợp:
    + Muốn sử dụng full data để train thì: 
    
        data = df_data.copy()
    
    + Muốn sử dụng data sau khi lọc thì:
    
        data = df_clean.copy()
    

In [58]:
data = df_clean.copy()

## 1. Slipt data into train and test

### 1.1 Slipt train and test

In [59]:
# Create training and validation sets
from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(
    data, 
    test_size=0.2, 
    random_state=42)
print("Train data shape:", train_data.shape)
print("Test data shape:", test_data.shape)

Train data shape: (3208, 6)
Test data shape: (803, 6)


In [60]:
train_data.to_csv("./Data/train_data.csv", index=False)
test_data.to_csv("./Data/test_data.csv", index=False)

### 1.2 Extract label is gia and drop in feature

In [61]:
y_train = train_data['gia'].values
y_test = test_data['gia'].values
train_data = train_data.drop(columns=['gia'], axis=1)
test_data = test_data.drop(columns=['gia'], axis=1)

In [62]:
train_data.shape, test_data.shape

((3208, 5), (803, 5))

### 1.3 Check train data having value is non-numeric or other type

In [63]:
num_cols = [col for col in train_data.columns if train_data[col].dtype in ["float64","int64"]]
cat_cols = [col for col in train_data.columns if train_data[col].dtype not in ["float64","int64"]]

In [64]:
len(num_cols), len(cat_cols)

(4, 1)

In [65]:
# fill none for categorical columns
train_data[cat_cols] = train_data[cat_cols].fillna("none")
test_data[cat_cols] = test_data[cat_cols].fillna("none")

In [66]:
print("X_train shape:", train_data.shape)
print("X_test shape:", test_data.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (3208, 5)
X_test shape: (803, 5)
y_train shape: (3208,)
y_test shape: (803,)


### 1.4 One-hot encoding feature "quan"

+ Nếu gặp một cái mới ở test thì set one-hot là 0

#### 1.4.1 One-hot encoding with catery in "quan"

In [67]:
from sklearn.preprocessing import OneHotEncoder

### One-hot encoding feature "quan"
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoder.fit(train_data[cat_cols])

encoder_cols = list(encoder.get_feature_names_out(cat_cols))
train_data[encoder_cols] = encoder.transform(train_data[cat_cols])
test_data[encoder_cols] = encoder.transform(test_data[cat_cols])

#### Transform value "Nan":

In [68]:
from sklearn.preprocessing import OneHotEncoder

# One-hot encode categorical columns
encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
encoder.fit(train_data[cat_cols])

encoded_cols = list(encoder.get_feature_names_out(cat_cols))

train_data[encoded_cols] = encoder.transform(train_data[cat_cols])
test_data[encoded_cols] = encoder.transform(test_data[cat_cols])

#### 1.4.2 Print information

In [69]:
train_data

quan  dien_tich_dat_m2  dien_tich_su_dung_m2  \
650                       4              55.0                 165.0   
1534                      8              53.0                  53.0   
2339                     12              30.0                  50.0   
1702                      8             120.0                 600.0   
1699                      8              61.0                 122.0   
...                     ...               ...                   ...   
1182                      6              80.0                  80.0   
1357                      7              60.0                 120.0   
901                       5              68.0                 136.0   
3751  Thủ Đức (TP. Thủ Đức)              20.0                  31.0   
3395                Tân Phú             127.0                 381.0   

      phong_ngu  nha_tam  quan_1  quan_10  quan_11  quan_12  quan_2  ...  \
650         4.0      3.0     0.0      0.0      0.0      0.0     0.0  ...   
1534        2.0      2.0     0.0      0.0      0.0      0.0     0.0  ...   
2339        2.0      2.0     0.0      0.0      0.0      1.0     0.0  ...   
1702        3.0      4.0     0.0      0.0      0.0      0.0     0.0  ...   
1699        3.0      2.0     0.0      0.0      0.0      0.0     0.0  ...   
...         ...      ...     ...      ...      ...      ...     ...  ...   
1182        2.0      2.0     0.0      0.0      0.0      0.0     0.0  ...   
1357        3.0      3.0     0.0      0.0      0.0      0.0     0.0  ...   
901         2.0      2.0     0.0      0.0      0.0      0.0     0.0  ...   
3751        2.0      1.0     0.0      0.0      0.0      0.0     0.0  ...   
3395        3.0      3.0     0.0      0.0      0.0      0.0     0.0  ...   

      quan_7  quan_8  quan_9  quan_Bình Thạnh  quan_Bình Tân  quan_Gò Vấp  \
650      0.0     0.0     0.0              0.0            0.0          0.0   
1534     0.0     1.0     0.0              0.0            0.0          0.0   
2339     0.0     0.0     0.0              0.0            0.0          0.0   
1702     0.0     1.0     0.0              0.0            0.0          0.0   
1699     0.0     1.0     0.0              0.0            0.0          0.0   
...      ...     ...     ...              ...            ...          ...   
1182     0.0     0.0     0.0              0.0            0.0          0.0   
1357     1.0     0.0     0.0              0.0            0.0          0.0   
901      0.0     0.0     0.0              0.0            0.0          0.0   
3751     0.0     0.0     0.0              0.0            0.0          0.0   
3395     0.0     0.0     0.0              0.0            0.0          0.0   

      quan_Phú Nhuận  quan_Thủ Đức (TP. Thủ Đức)  quan_Tân Bình  quan_Tân Phú  
650              0.0                         0.0            0.0           0.0  
1534             0.0                         0.0            0.0           0.0  
2339             0.0                         0.0            0.0           0.0  
1702             0.0                         0.0            0.0           0.0  
1699             0.0                         0.0            0.0           0.0  
...              ...                         ...            ...           ...  
1182             0.0                         0.0            0.0           0.0  
1357             0.0                         0.0            0.0           0.0  
901              0.0                         0.0            0.0           0.0  
3751             0.0                         1.0            0.0           0.0  
3395             0.0                         0.0            0.0           1.0  

[3208 rows x 24 columns]

In [70]:
test_data

quan  dien_tich_dat_m2  dien_tich_su_dung_m2  phong_ngu  nha_tam  \
336            2              72.0                  72.0        2.0      2.0   
2753  Bình Thạnh             249.0                1000.0        7.0      7.0   
3090   Phú Nhuận              64.0                 128.0        3.0      4.0   
2629    Bình Tân              96.0                  96.0        2.0      1.0   
3470     Tân Phú              32.0                  60.0        2.0      2.0   
...          ...               ...                   ...        ...      ...   
1482           7             140.0                 140.0        5.0      5.0   
294            2              98.0                  98.0        2.0      2.0   
743            4             105.0                 105.0        3.0      2.0   
285            2             433.0                 433.0        4.0      4.0   
3186   Phú Nhuận              43.0                 120.0        4.0      5.0   

      quan_1  quan_10  quan_11  quan_12  quan_2  ...  quan_7  quan_8  quan_9  \
336      0.0      0.0      0.0      0.0     1.0  ...     0.0     0.0     0.0   
2753     0.0      0.0      0.0      0.0     0.0  ...     0.0     0.0     0.0   
3090     0.0      0.0      0.0      0.0     0.0  ...     0.0     0.0     0.0   
2629     0.0      0.0      0.0      0.0     0.0  ...     0.0     0.0     0.0   
3470     0.0      0.0      0.0      0.0     0.0  ...     0.0     0.0     0.0   
...      ...      ...      ...      ...     ...  ...     ...     ...     ...   
1482     0.0      0.0      0.0      0.0     0.0  ...     1.0     0.0     0.0   
294      0.0      0.0      0.0      0.0     1.0  ...     0.0     0.0     0.0   
743      0.0      0.0      0.0      0.0     0.0  ...     0.0     0.0     0.0   
285      0.0      0.0      0.0      0.0     1.0  ...     0.0     0.0     0.0   
3186     0.0      0.0      0.0      0.0     0.0  ...     0.0     0.0     0.0   

      quan_Bình Thạnh  quan_Bình Tân  quan_Gò Vấp  quan_Phú Nhuận  \
336               0.0            0.0          0.0             0.0   
2753              1.0            0.0          0.0             0.0   
3090              0.0            0.0          0.0             1.0   
2629              0.0            1.0          0.0             0.0   
3470              0.0            0.0          0.0             0.0   
...               ...            ...          ...             ...   
1482              0.0            0.0          0.0             0.0   
294               0.0            0.0          0.0             0.0   
743               0.0            0.0          0.0             0.0   
285               0.0            0.0          0.0             0.0   
3186              0.0            0.0          0.0             1.0   

      quan_Thủ Đức (TP. Thủ Đức)  quan_Tân Bình  quan_Tân Phú  
336                          0.0            0.0           0.0  
2753                         0.0            0.0           0.0  
3090                         0.0            0.0           0.0  
2629                         0.0            0.0           0.0  
3470                         0.0            0.0           1.0  
...                          ...            ...           ...  
1482                         0.0            0.0           0.0  
294                          0.0            0.0           0.0  
743                          0.0            0.0           0.0  
285                          0.0            0.0           0.0  
3186                         0.0            0.0           0.0  

[803 rows x 24 columns]

# III Normalization

+ Mục tiêu đưa các giá trị về [0, 1]
+ Chuẩn hoá theo min, max
+ value_new = (value_old - min)/(max - min)

## 1. Normalization

In [71]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

train_num_feature = scaler.fit_transform(train_data[num_cols])
test_num_feature = scaler.transform(test_data[num_cols])

In [72]:
print("X_train shape:", train_num_feature.shape)
print("X_test shape:", test_num_feature.shape)

X_train shape: (3208, 4)
X_test shape: (803, 4)


In [73]:
train_num_feature

array([[0.05405405, 0.08204102, 0.33333333, 0.22222222],
       [0.05205205, 0.02601301, 0.11111111, 0.11111111],
       [0.02902903, 0.02451226, 0.11111111, 0.11111111],
       ...,
       [0.06706707, 0.06753377, 0.11111111, 0.11111111],
       [0.01901902, 0.0150075 , 0.11111111, 0.        ],
       [0.12612613, 0.19009505, 0.22222222, 0.22222222]])

In [74]:
test_num_feature

array([[0.07107107, 0.03551776, 0.11111111, 0.11111111],
       [0.24824825, 0.49974987, 0.66666667, 0.66666667],
       [0.06306306, 0.06353177, 0.22222222, 0.33333333],
       ...,
       [0.1041041 , 0.05202601, 0.22222222, 0.11111111],
       [0.43243243, 0.21610805, 0.33333333, 0.33333333],
       [0.04204204, 0.05952976, 0.33333333, 0.44444444]])

## 2. Add X_train, X_test in stack follow horizontal

+ Mục tiêu: nối theo chiều ngang (mảng các vector).

In [75]:
X_train = np.hstack([train_num_feature, train_data[encoder_cols].values])
X_test = np.hstack([test_num_feature, test_data[encoder_cols].values])

In [76]:
X_train.shape, X_test.shape

((3208, 23), (803, 23))

In [77]:
X_train

array([[0.05405405, 0.08204102, 0.33333333, ..., 0.        , 0.        ,
        0.        ],
       [0.05205205, 0.02601301, 0.11111111, ..., 0.        , 0.        ,
        0.        ],
       [0.02902903, 0.02451226, 0.11111111, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.06706707, 0.06753377, 0.11111111, ..., 0.        , 0.        ,
        0.        ],
       [0.01901902, 0.0150075 , 0.11111111, ..., 1.        , 0.        ,
        0.        ],
       [0.12612613, 0.19009505, 0.22222222, ..., 0.        , 0.        ,
        1.        ]])

In [78]:
X_test

array([[0.07107107, 0.03551776, 0.11111111, ..., 0.        , 0.        ,
        0.        ],
       [0.24824825, 0.49974987, 0.66666667, ..., 0.        , 0.        ,
        0.        ],
       [0.06306306, 0.06353177, 0.22222222, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.1041041 , 0.05202601, 0.22222222, ..., 0.        , 0.        ,
        0.        ],
       [0.43243243, 0.21610805, 0.33333333, ..., 0.        , 0.        ,
        0.        ],
       [0.04204204, 0.05952976, 0.33333333, ..., 0.        , 0.        ,
        0.        ]])

In [79]:
y_train

array([ 1.1  ,  1.739,  1.38 , ...,  1.24 ,  1.8  , 19.5  ])

In [80]:
y_test

array([5.99900e+00, 6.30000e+01, 5.00000e+01, 7.98000e+00, 3.59000e+00,
       2.45500e+00, 6.50000e+00, 1.55000e+01, 2.90000e+00, 9.80000e+00,
       4.60000e+00, 9.28000e-01, 8.60000e+00, 1.80000e+01, 1.45000e+01,
       4.50000e+00, 7.50000e+00, 5.90000e+01, 2.69000e+00, 1.89000e+00,
       8.80000e-01, 2.65000e+01, 2.25000e+01, 5.10000e+00, 3.40000e+01,
       5.90000e+00, 3.60000e+01, 4.30000e+00, 2.75000e+00, 7.90000e+00,
       9.70000e-01, 9.50000e+00, 4.80000e+00, 9.98000e+00, 1.10000e+01,
       6.70000e+00, 1.90000e+01, 2.00000e+01, 3.20000e+00, 1.68000e+01,
       1.50000e+01, 8.70000e+00, 1.70500e+00, 1.03300e+00, 7.80000e+01,
       8.90000e+00, 1.00000e-01, 8.90000e+00, 1.20000e+01, 3.35000e+01,
       5.35000e+00, 6.58000e+00, 9.90000e+00, 4.40000e+00, 9.10000e+00,
       2.80000e+01, 1.29000e+01, 5.00000e+01, 7.95000e+00, 3.79990e+01,
       6.99900e+00, 9.70000e-01, 2.30000e+01, 2.28000e+00, 1.55000e+01,
       2.25000e+01, 3.60000e+01, 3.95000e+00, 5.50000e+00, 8.200

# IV Polynomial Feature Engineer model

In [81]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, MinMaxScaler, PolynomialFeatures
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
from sklearn.base import BaseEstimator, TransformerMixin
import joblib
import os

# 1. Định nghĩa Class biến đổi dữ liệu (FeatureEngineer)
class FeatureEngineer(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self
    
    def transform(self, X):
        if isinstance(X, np.ndarray):
            feature_names = ['dien_tich_dat_m2', 'dien_tich_su_dung_m2', 'phong_ngu', 'nha_tam', 'quan']
            X = pd.DataFrame(X, columns=feature_names)
            
        X_new = X.copy()
        X_new['dien_tich_trung_binh_phong'] = X_new['dien_tich_su_dung_m2'] / (X_new['phong_ngu'] + 1e-5)
        X_new['tong_so_phong'] = X_new['phong_ngu'] + X_new['nha_tam']
        return X_new

# 2. Hàm huấn luyện và đánh giá
def train_polynomial_model(X_train, y_train, X_test, y_test):
    """
    Hàm xây dựng, huấn luyện mô hình Polynomial Regression với Feature Engineering 
    và trả về kết quả đánh giá chi tiết dạng DataFrame.
    """
    
    # --- 1. Định nghĩa các cột ---
    num_cols_base = ["dien_tich_dat_m2", "dien_tich_su_dung_m2", "phong_ngu", "nha_tam"]
    cat_cols = ["quan"]
    num_cols_eng = num_cols_base + ["dien_tich_trung_binh_phong", "tong_so_phong"]

    # --- 2. Xây dựng Transformers ---
    numeric_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="mean")),
        ("poly", PolynomialFeatures(degree=2, include_bias=False)),
        ("scaler", MinMaxScaler())
    ])

    categorical_transformer = Pipeline(steps=[
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore"))
    ])

    # --- 3. Preprocessor ---
    preprocessor = ColumnTransformer(
        transformers=[
            ("num", numeric_transformer, num_cols_eng),
            ("cat", categorical_transformer, cat_cols),
        ]
    )

    # --- 4. Pipeline ---
    model_pipeline = Pipeline(steps=[
        ("feature_eng", FeatureEngineer()), 
        ("preprocessor", preprocessor),     
        ("regressor", LinearRegression())   
    ])

    # --- 5. Huấn luyện ---
    if isinstance(y_train, np.ndarray):
        y_train = pd.Series(y_train, name='gia')
        
    model_pipeline.fit(X_train, y_train)
    
    # --- 6. Đánh giá (Tính toán Metrics) ---
    y_train_pred = model_pipeline.predict(X_train)
    y_test_pred = model_pipeline.predict(X_test)
    
    train_rmse = np.sqrt(mean_squared_error(y_train, y_train_pred))
    test_rmse = np.sqrt(mean_squared_error(y_test, y_test_pred))
    train_r2 = r2_score(y_train, y_train_pred)
    test_r2 = r2_score(y_test, y_test_pred)
    
    # --- 7. Tạo DataFrame kết quả ---
    results_df = pd.DataFrame({
        "Model": ["Polynomial_FeatureEng"],
        "Train RMSE": [train_rmse],
        "Test RMSE": [test_rmse],
        "Train R2": [train_r2],
        "Test R2": [test_r2]
    })
    
    print("Huấn luyện và đánh giá hoàn tất.")
    return model_pipeline, results_df

# --- Cách sử dụng ---
# model, result_df = train_polynomial_model(X_train, y_train, X_test, y_test)
# print(result_df)

# 3. Lưu mô hình bằng joblib
# Tạo thư mục Models nếu chưa có
folder_path_save = "Models"
if not os.path.exists(folder_path_save):
    os.makedirs(folder_path_save)

# Đặt tên file mô hình
model_filename = f"{folder_path_save}/house_price_Polynomial_FeatureEng_model.joblib"

# Lưu file
folder_path_save = "Models"
if not os.path.exists(folder_path_save):
    os.makedirs(folder_path_save)
joblib.dump(model, model_filename)


['Models/house_price_Polynomial_FeatureEng_model.joblib']

Tham số của mô hình

In [82]:
import pandas as pd
import numpy as np
import joblib
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.compose import ColumnTransformer
# Import các thuật toán để kiểm tra
from sklearn.linear_model import LinearRegression, Ridge, Lasso, HuberRegressor 

# --- 1. BẮT BUỘC: Định nghĩa lại Class FeatureEngineer ---
class FeatureEngineer(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        if isinstance(X, np.ndarray):
            feature_names = [f"col_{i}" for i in range(X.shape[1])]
            if len(feature_names) == 5:
                 feature_names = ['dien_tich_dat_m2', 'dien_tich_su_dung_m2', 'phong_ngu', 'nha_tam', 'quan']
            X = pd.DataFrame(X, columns=feature_names)
        
        X_new = X.copy()
        if all(col in X_new.columns for col in ['dien_tich_su_dung_m2', 'phong_ngu', 'nha_tam']):
             X_new['dien_tich_trung_binh_phong'] = X_new['dien_tich_su_dung_m2'] / (X_new['phong_ngu'] + 1e-5)
             X_new['tong_so_phong'] = X_new['phong_ngu'] + X_new['nha_tam']
        return X_new

# --- 2. Load Model ---
model_path = "Models/house_price_Polynomial_FeatureEng_model.joblib"
try:
    model = joblib.load(model_path)
    print(f"Đã load model từ: {model_path}")
    # In ra tên các bước để bạn kiểm tra (Ví dụ: 'preprocess', 'regressor')
    print("Các bước trong Pipeline:", list(model.named_steps.keys())) 
except Exception as e:
    print(f"Lỗi load model: {e}")
    # Tạo model giả để code dưới không crash khi demo
    exit()

# --- 3. TỰ ĐỘNG TÌM CÁC BƯỚC (FIX LỖI KEY ERROR & NAME ERROR) ---
preprocessor_step = None
regressor_step = None

for name, step in model.named_steps.items():
    # Tìm bước tiền xử lý (ColumnTransformer)
    if isinstance(step, ColumnTransformer):
        preprocessor_step = step
    
    # Tìm bước huấn luyện (Có thuộc tính coef_ hoặc là các class mô hình)
    # Lưu ý: Đã import HuberRegressor ở trên nên sẽ không bị lỗi NameError nữa
    if hasattr(step, 'coef_') or isinstance(step, (LinearRegression, Ridge, Lasso, HuberRegressor)):
        regressor_step = step

if preprocessor_step is None or regressor_step is None:
    print("LỖI: Không tìm thấy Preprocessor hoặc Regressor. Hãy kiểm tra lại Pipeline.")
else:
    # --- 4. HIỂN THỊ THAM SỐ ---
    print("\n" + "="*30)
    print("THAM SỐ CỦA MÔ HÌNH")
    print("="*30)

    # A. Hệ số chặn (Intercept)
    # Một số mô hình như Huber có thể không có intercept_, cần dùng getattr để an toàn
    intercept = getattr(regressor_step, 'intercept_', 0.0)
    print(f"Hệ số chặn (Intercept/Bias): {intercept:.4f}")

    # B. Lấy tên đặc trưng (Features)
    try:
        feature_names = preprocessor_step.get_feature_names_out()
    except Exception as e:
        print(f"Dùng index thay thế tên đặc trưng (Lỗi: {e})")
        feature_names = [f"Feature_{i}" for i in range(len(regressor_step.coef_))]

    # C. Tạo DataFrame tham số
    if len(feature_names) == len(regressor_step.coef_):
        params_df = pd.DataFrame({
            'Feature_Name': feature_names,
            'Coefficient (Weight)': regressor_step.coef_
        })

        # Sắp xếp theo độ tác động tuyệt đối
        params_df['Impact_Level'] = params_df['Coefficient (Weight)'].abs()
        params_df = params_df.sort_values(by='Impact_Level', ascending=False).drop(columns=['Impact_Level'])

        print("\nTham số từng đặc trưng:")
        # Làm sạch tên cột
        params_df['Feature_Name'] = params_df['Feature_Name'].astype(str).str.replace('num__', '').str.replace('cat__', '')
        print(params_df.to_string(index=False))
    else:
        print(f"Lệch kích thước: {len(feature_names)} tên đặc trưng vs {len(regressor_step.coef_)} hệ số.")

Đã load model từ: Models/house_price_Polynomial_FeatureEng_model.joblib
Các bước trong Pipeline: ['preprocess', 'regressor']

THAM SỐ CỦA MÔ HÌNH
Hệ số chặn (Intercept/Bias): -33.1865

Tham số từng đặc trưng:
                         Feature_Name  Coefficient (Weight)
dien_tich_dat_m2 dien_tich_su_dung_m2           -545.425448
         dien_tich_su_dung_m2 nha_tam            519.940977
                     dien_tich_dat_m2            512.072448
       dien_tich_su_dung_m2 phong_ngu           -474.422872
             dien_tich_dat_m2 nha_tam           -346.606703
           dien_tich_dat_m2 phong_ngu            296.619008
                 dien_tich_su_dung_m2            126.786294
                               quan_4             77.435809
                            phong_ngu             66.507233
                    phong_ngu nha_tam            -56.964575
                               quan_3             32.707401
                               quan_1             28.337152
           